### ISSUE TITLE
Mobile (S5 screen size) - Getting started screen is broken due to the video size

### ISSUE THREAD

**Issue by davidffrench** [aerogear/aerogear.org#760]
**Link:** https://aerogear.org/getting-started/
**Device Emulation:** Galaxy S5
**Screen Size:** 360 x 640

![2018-07-12_10-27-13](https://user-images.githubusercontent.com/1596014/42624819-3be55a6a-85be-11e8-9a5c-4e48fabb80cc.gif)

**Comment by danielpassos** [comment]
Closing since we don't have video on that page anymore. Feel free to reopen if we still having this problem
