### ISSUE TITLE
Broken link to community contributor guide

### ISSUE THREAD

**Issue by laurafitzgerald** [aerogear/aerogear.org#776]
## Description
Some broken links to the Contributing Guide

## Expected Behavior
Link should work

## Actual Behavior
Link doesn't work

## Steps to reproduce
Click the link titled `this link` in the source repository section.

**Comment by danielpassos** [comment]
@laurafitzgerald The PR linked is already merge, is it still valid? Should we close it?

**Comment by laurafitzgerald** [comment]
Yes let's close it.
